version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
      # Add any commands needed to install dependencies for your project

  pre_build:
    commands:
      - echo "Pre-build phase..."
      # Add any commands needed before the build process

  build:
    commands:
      - echo "Building the application..."
      # Add the commands needed to build your application (e.g., compile code, package artifacts)

artifacts:
  files: 
    - '**/*'
  name: my-application-artifact
  discard-paths: yes
  # You might need to adjust the 'files' pattern based on your project structure

cache:
  paths:
    - '/root/.m2/**/*'
    # Add any other paths that can be cached to speed up the build process
