version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify a valid Node.js version

  pre_build:
    commands:
      - echo "Starting the build"

  build:
    commands:
      - echo "Building the application"

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files: '**/*'
