version: 0.2

pipelines:
  default:
    - name: HelloWorldPipeline
      steps:
        - name: Source
          action: aws-codepipeline-source-action
          outputs:
            - MySourceOutput
          configuration:
            BranchName: main
            RepositoryName: https://github.com/kunalbhagwat0/Helloworld

        - name: Build
          action: aws-codepipeline-build-action
          inputs:
            - MySourceOutput
          outputs:
            - BuildOutput

        - name: Deploy
          action: aws-codepipeline-deploy-to-ecs-action
          inputs:
            - BuildOutput
          configuration:
            ClusterName: DevStaxxx
            ServiceName: service-tho-hai
            Image1ArtifactName: BuildOutput::random.json
            Image1ContainerName: chalo
            Image1RegistryName: 425302025161.dkr.ecr.sp-south-1.amazonaws.com/hello-xxxxx
