version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing AWS CLI...
      - yum install -y aws-cli

  build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region ap-south-1)

      # Rest of your build commands

artifacts:
  files: '*'
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.gradle/**/*'
